# Generated by Django 5.2.5 on 2025-08-17 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietarygoal",
            name="fiber_consumed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="fiber_target",
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="last_reset_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="sodium_consumed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="sodium_target",
            field=models.IntegerField(default=2300),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="sugar_consumed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="sugar_target",
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name="DailyNutritionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("calories", models.IntegerField(default=0)),
                ("protein", models.IntegerField(default=0)),
                ("fat", models.IntegerField(default=0)),
                ("carbs", models.IntegerField(default=0)),
                ("sugar", models.IntegerField(default=0)),
                ("sodium", models.IntegerField(default=0)),
                ("fiber", models.IntegerField(default=0)),
                ("goals_met", models.IntegerField(default=0)),
                ("total_goals", models.IntegerField(default=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyNutritionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("avg_calories", models.FloatField(default=0)),
                ("avg_protein", models.FloatField(default=0)),
                ("avg_fat", models.FloatField(default=0)),
                ("avg_carbs", models.FloatField(default=0)),
                ("avg_sugar", models.FloatField(default=0)),
                ("avg_sodium", models.FloatField(default=0)),
                ("avg_fiber", models.FloatField(default=0)),
                ("calories_achievement", models.FloatField(default=0)),
                ("protein_achievement", models.FloatField(default=0)),
                ("fat_achievement", models.FloatField(default=0)),
                ("carbs_achievement", models.FloatField(default=0)),
                ("sugar_achievement", models.FloatField(default=0)),
                ("sodium_achievement", models.FloatField(default=0)),
                ("fiber_achievement", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start_date"],
                "unique_together": {("user", "week_start_date")},
            },
        ),
    ]
