# Generated by Django 5.2.5 on 2025-08-18 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_dietarygoal_fiber_consumed_dietarygoal_fiber_target_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalizedTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip_type",
                    models.CharField(
                        choices=[
                            ("critical", "Critical Alert"),
                            ("warning", "Warning"),
                            ("success", "Success"),
                            ("info", "Information"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "High"),
                            (3, "Medium"),
                            (4, "Low"),
                        ],
                        default=3,
                    ),
                ),
                ("icon", models.CharField(default="info-circle", max_length=50)),
                ("color", models.CharField(default="info", max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_nutrition_snapshot", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("trigger_condition", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalized_tips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-created_at"],
                "unique_together": {("user", "trigger_condition")},
            },
        ),
    ]
