# Generated by Django 5.2.5 on 2025-08-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_trackeditem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="personalizedtip",
            unique_together=set(),
        ),
    ]
