# Generated by Django 5.2.5 on 2025-08-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
